spring:
  application:
    name: pharma-customer-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/smartpharmadb?searchpath=customer_schema
    username: postgres
    password: panchakshari
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

springdoc:
  api-docs:
    path: /swagger-ui.html